spring:
  application:
    name: Auth-Route-Services
logging:
  level:
    ROOT: INFO
    io.pivotal.poc.bac: DEBUG
login:
  url: https://pivotal.io/
sm:
  ip: 192.168.1.100
  user: username
  password: password
  agent:
    hostname: pivotal-cf