spring:
  application:
    name: Auth-Route-Services
logging:
  level:
    ROOT: INFO
    io.pivotal.poc.bac: DEBUG
login:
  url: https://pivotal.io/
sm:
  ip: vp6.casecurecenter.com
  user: user
  password: pwd
  agent:
    name: spsagent
    hostname: pivotal-cf